[build]
  # No build command needed - static files only
  publish = "."
  
[build.environment]
  # No environment variables needed

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Special caching for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache JSON config files for shorter time
  for = "/config/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Cache dictionary file
  for = "/assets/*.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirect rules for SPA behavior (if needed)
[[redirects]]
  from = "/game/*"
  to = "/index.html"
  status = 200

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404